name = "trip-planner"
pages_build_output_dir = "./dist"

# This applies to local development
[[d1_databases]]
binding = "DB" # The variable name you will use in your code (e.g., env.DB)
database_name = "trips"
database_id = "838d7c39-1f6d-4ca6-acbe-2e4c0e8ddd63"

# This applies to live GitHub production deployment
[env.production]
[[env.production.d1_databases]]
binding = "DB"
database_name = "trips"
database_id = "838d7c39-1f6d-4ca6-acbe-2e4c0e8ddd63"
